version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install-lint-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Install Dependencies
                command: npm install
            - run:
                name: Lint Code
                command: npm run lint
            - run:
                name: Test Changes
                command: npm test
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Build Production
                command: npm run build
  lighthouse:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: sudo npm install -g @lhci/cli@0.3.x
      - run: lhci autorun —config=../src/config/lighthouserc.json
workflows:
    install-and-deploy:
      jobs:
        - install-lint-test
        - build
        - lighthouse