version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Install Dependencies
                command: npm install
            - run:
                name: Test Changes
                command: npm test
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Build Production
                command: npm run build
workflows:
    install-and-deploy:
      jobs:
        - install-and-test
        - build-and-deploy